version: '2'
services:
  apachephp53:
    build: apache-php53/
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - ./code:/var/www
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=oxid
    ports:
      - 3306:3306
